Dependencies:
  - 'FOSUserBundle'
AppKernel:
  - 'new JMS\DiExtraBundle\JMSDiExtraBundle()'
  - 'new JMS\AopBundle\JMSAopBundle()'
Composer:
    name: doctrine/doctrine-fixtures-bundle
    version : "~2.0@dev"